name: Property Testings

on:
  schedule:
    - cron: "0 */4 * * *"
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  property-testing:
    name: Property Testing
    runs-on: ubuntu-latest
    env:
      PROPTEST_CASES: 2
    steps:
      - name: Checkout PR
        uses: actions/checkout@v4

      - name: Use Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: Run
        run: |
          set +e
          cargo test --test wasm-generation --test standard | tee output.log
          test_exit=${PIPESTATUS[0]}
          echo "Extracting relevant section from test output:"
          echo "output.log: $(cat output.log)"
          grep -A 50 "Test failed: assertion \left == right\ failed" output.log >> $GITHUB_WORKSPACE/failure_section.log
          echo "failure_section.log: $(cat $GITHUB_WORKSPACE/failure_section.log)"
          echo "failure_section=$(cat $GITHUB_WORKSPACE/failure_section.log)" >> $GITHUB_ENV
          # Check if failure_section.log has content
          if [ -s $GITHUB_WORKSPACE/failure_section.log ]; then
            exit 101
          fi
          # Also exit with 101 if cargo test failed
          if [ $test_exit -ne 0 ]; then
            exit 101
          fi

      - name: Check failure_section.log
        if: ${{ failure() }}
        run: |
          cat $GITHUB_WORKSPACE/failure_section.log
          echo $GITHUB_WORKSPACE/failure_section.log

      - name: Create GitHub Issue on Failure
        uses: jayqi/failed-build-issue-action@v1
        if: ${{ failure() }}
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          label-name: "property-testing-failure"
          title-template: "Property testing failure"
          body-template: |
            GitHub Actions workflow [{{workflow}} #{{runNumber}}](https://github.com/{{repo.owner}}/{{repo.repo}}/actions/runs/{{runId}}) failed.
            ```
            ${{ env.failure_section }}
            ```

      - name: Send message to Slack
        uses: slackapi/slack-github-action@37ebaef184d7626c5f204ab8d3baff4262dd30f0 # v1.27.0
        if: ${{ failure() }}
        with:
          channel-id: ${{ secrets.CHANNEL_ID }}
          payload: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "GitHub Actions workflow <https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}|Property Testing #${{ github.run_number }}> failed."
                  }
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
