name: Property Testings

on:
  schedule:
    - cron: "0 */4 * * *"
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  property-testing:
    name: Property Testing
    runs-on: ubuntu-latest
    env:
      PROPTEST_CASES: 100
    steps:
      - name: Checkout PR
        uses: actions/checkout@v4

      - name: Use Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: Run
        run: cargo test --test wasm-generation --test standard

      - name: Add link to the failure issue
        uses: jayqi/failed-build-issue-action@v1
        if: ${{ failure() }}
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          label-name: "property-testing-failure"
          title-template: "Property testing coverage has failed"
          body-template: |
            GitHub Actions workflow [{{workflow}} #{{runNumber}}](https://github.com/{{repo.owner}}/{{repo.repo}}/actions/runs/{{runId}}) failed.

      - name: Send message to Slack
        uses: slackapi/slack-github-action@v1.27.0
        if: ${{ failure() }}
        with:
          channel-id: ${{ secrets.CHANNEL_ID }}
          payload: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "GitHub Actions workflow <https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}|Property Testing #${{ github.run_number }}> failed."
                  }
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
