name: Property Testings

on:
  schedule:
    - cron: "0 */4 * * *"
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  property-testing:
    name: Property Testing
    runs-on: ubuntu-latest
    env:
      PROPTEST_CASES: 2
    steps:
      - name: Checkout PR
        uses: actions/checkout@v4

      - name: Use Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: Run
        run: |
          cargo test --test wasm-generation --test standard

      - name: Retrieve Job ID
        id: get_job_id
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          RUN_ID: ${{ github.run_id }}
          JOB_NAME: ${{ github.job }}
        run: |
          job_id=$(curl -s -H "Authorization: token ${GITHUB_TOKEN}" \
          "https://api.github.com/repos/${GITHUB_REPOSITORY}/actions/runs/${RUN_ID}/jobs" \
          | jq -r ".jobs[] | select(.name == \"${JOB_NAME}\") | .id")
          echo "job_id=$job_id" >> $GITHUB_ENV

      - name: Create GitHub Issue on Failure
        uses: jayqi/failed-build-issue-action@v1
        if: ${{ failure() }}
        env:
          JOB_ID: ${{ env.job_id }}
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          label-name: "property-testing-failure"
          title-template: "Property testing failure"
          body-template: |
            GitHub Actions workflow [{{workflow}} #{{runNumber}}](https://github.com/{{repo.owner}}/{{repo.repo}}/actions/runs/{{runId}}/job/{{JOB_ID}}) failed.

      - name: Send message to Slack
        uses: slackapi/slack-github-action@37ebaef184d7626c5f204ab8d3baff4262dd30f0 # v1.27.0
        if: ${{ failure() }}
        with:
          channel-id: ${{ secrets.CHANNEL_ID }}
          payload: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "GitHub Actions workflow <https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}|Property Testing #${{ github.run_number }}> failed."
                  }
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
