name: Property Testings

on:
  schedule:
    - cron: "0 */4 * * *"
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  property-testing:
    name: Property Testing
    runs-on: ubuntu-latest
    env:
      PROPTEST_CASES: 100
    steps:
      - name: Checkout PR
        uses: actions/checkout@v4

      - name: Use Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: Run
        run: cargo test --test wasm-generation --test standard

      - name: Add link to the failure issue
        uses: jayqi/failed-build-issue-action@v1
        if: ${{ failure() }}
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          label-name: "property-testing-failure"
          title-template: "Property testing coverage has failed"
          body-template: |
            GitHub Actions workflow [{{workflow}} #{{runNumber}}](https://github.com/{{repo.owner}}/{{repo.repo}}/actions/runs/{{runId}}) failed.

      - name: Add link to the failure issue
        uses: slackapi/slack-github-action@v1.27.0
        id: slack
        if: ${{ failure() }}
        with:
          # Slack channel id, channel name, or user id to post message.
          # See also: https://api.slack.com/methods/chat.postMessage#channels
          # You can pass in multiple channels to post to by providing a comma-delimited list of channel IDs.
          channel-id: "C07UBHQEJLR"
          # For posting a simple plain text message
          slack-message: "GitHub build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
